name: pacifickode
description: "Practicle Test"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1

  # Navigation
  go_router: ^16.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

